# Generated by Django 5.0.1 on 2024-01-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_payment', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], max_length=50, verbose_name='метод оплаты')),
                ('card_type', models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('mir', 'Мир')], max_length=50, null=True, verbose_name='тип карты')),
                ('owner_full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, verbose_name='телефон')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='лимит')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачена'), ('canceled', 'Отменена')], max_length=50, verbose_name='статус')),
                ('requisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.requisite', verbose_name='реквизит')),
            ],
            options={
                'verbose_name': 'Запрос на оплату',
                'verbose_name_plural': 'Запросы на оплату',
            },
        ),
    ]
